### ISSUE TITLE
🤔 Default status code for multiple possible statusCode values

### ISSUE THREAD

**Issue by nicolasgramlich** [bluebirds-blue-jay/inversify-controller#7]
I converted a few endpoints to have multiple possible `@response({statusCode` values like this:
```
  @response({
    statusCode: [StatusCode.CREATED, StatusCode.CONFLICT],
```

then suddenly the logic falls back to `StatusCode.OK`, maybe we should assume the first entry to be the default status code if it's an Array?
https://github.com/bluebirds-blue-jay/inversify-controller/blob/d62bc16cdbe4a229249b62e4f95070f0c2324b56/src/decorators/json-response.ts#L35-L37

**Comment by SylvainEstevez** [comment]
That would be arbitrary and unclear. If you have multiple status codes, then you need to manually set the status code on the response.

However the status code property is not meant to describe errors. I have plans to support error responses as well but this is not supported at the moment.

**Comment by nicolasgramlich** [comment]
Maybe we could add `errorStatusCodes` 🤔 ?

**Comment by SylvainEstevez** [comment]
`errorResponses` to remain consistent but yes 👍
