### ISSUE TITLE
🐛 @query doesn't convert ISO Strings to Date objects

### ISSUE THREAD

**Issue by nicolasgramlich** [bluebirds-blue-jay/inversify-controller#9]

**Comment by SylvainEstevez** [comment]
See https://github.com/YousefED/typescript-json-schema/issues/98 about AJV. Bluejay simply proxies AJV for coercion, I'm not sure if I want to bring [custom keywords](https://ajv.js.org/custom.html) or if consumers should implement their own. Maybe that could be an option driven feature?

**Comment by SylvainEstevez** [comment]
Thinking about, Bluejay never does coercion - it's all managed by AJV - this is therefore not a Bluejay issue.
However it is not easy to define custom AJV instances (with custom keywords for example) without having to pass them to every decorator call currently, so a good thing would be to have a more global way to define AJV instances in order to allow consumers to define custom keywords.

**Comment by SylvainEstevez** [comment]
`@bluejay/inversify-controller@3.2.0` is now published and allows the following.

```typescript
import { Config } from '@bluejay/inversify-controller';
import * as AJV from 'ajv';

const queryAJV = new AJV({ coerceTypes: true, useDefaults: true });

Config.set('queryAJVFactory', () => queryAJV);
```

This will have for effect that all `@query()` decorators will use this particular instance.

In order to achieve the custom coercion, you can now do something like this.

```typescript
queryAJV.addKeyword('range', {
  type: 'number',
  compile: function (sch, parentSchema) {
    var min = sch[0];
    var max = sch[1];

    return parentSchema.exclusiveRange === true
            ? function (data) { return data > min && data < max; }
            : function (data) { return data >= min && data <= max; }
  },
  errors: false,
  metaSchema: {
    type: 'array',
    items: [
      { type: 'number' },
      { type: 'number' }
    ],
    additionalItems: false
  }
});
```

**Comment by SylvainEstevez** [comment]
See https://github.com/epoberezkin/ajv/issues/192#issuecomment-238975648 for a date coercion example.
